### ISSUE TITLE
Trouble Compiling in VS 2015

### ISSUE THREAD

**Issue by richrumble** [moullos/Mitigate#1]
These are the errors I get, "domain" is defined in the first few
1>------ Rebuild All started: Project: Mitigate, Configuration: Debug Any CPU ------
1>C:\Users\xxxxx\Downloads\Mitigate-master\UserUtils.cs(47,111,47,117): error CS1003: Syntax error, ',' expected
1>C:\Users\xxxxx\Downloads\Mitigate-master\UserUtils.cs(69,114,69,120): error CS1003: Syntax error, ',' expected
1>C:\Users\xxxxx\Downloads\Mitigate-master\UserUtils.cs(88,98,88,101): error CS1003: Syntax error, ',' expected
1>C:\Users\xxxxx\Downloads\Mitigate-master\UserUtils.cs(97,97,97,101): error CS1003: Syntax error, ',' expected
1>C:\Users\xxxxx\Downloads\Mitigate-master\UserUtils.cs(97,110,97,113): error CS1525: Invalid expression term 'int'
1>C:\Users\xxxxx\Downloads\Mitigate-master\UserUtils.cs(97,114,97,119): error CS1003: Syntax error, ',' expected
1>C:\Users\xxxxx\Downloads\Mitigate-master\UserUtils.cs(229,35,229,37): error CS1002: ; expected
1>C:\Users\xxxxx\Downloads\Mitigate-master\UserUtils.cs(229,35,229,37): error CS1519: Invalid token '=>' in class, struct, or interface member declaration
1>C:\Users\xxxxx\Downloads\Mitigate-master\UserUtils.cs(229,38,229,45): error CS1520: Method must have a return type
1>C:\Users\xxxxx\Downloads\Mitigate-master\UserUtils.cs(229,46,229,51): error CS1041: Identifier expected; 'false' is a keyword
1>C:\Users\xxxxx\Downloads\Mitigate-master\Utils.cs(276,26,276,30): error CS1031: Type expected
1>C:\Users\xxxxx\Downloads\Mitigate-master\Utils.cs(276,26,276,30): error CS1026: ) expected
1>C:\Users\xxxxx\Downloads\Mitigate-master\Utils.cs(276,30,276,31): error CS1002: ; expected
1>C:\Users\xxxxx\Downloads\Mitigate-master\Utils.cs(276,30,276,31): error CS1513: } expected
1>C:\Users\xxxxx\Downloads\Mitigate-master\Utils.cs(296,26,296,30): error CS1031: Type expected
1>C:\Users\xxxxx\Downloads\Mitigate-master\Utils.cs(296,26,296,30): error CS1026: ) expected
1>C:\Users\xxxxx\Downloads\Mitigate-master\Utils.cs(296,30,296,31): error CS1002: ; expected
1>C:\Users\xxxxx\Downloads\Mitigate-master\Utils.cs(296,30,296,31): error CS1513: } expected
1>C:\Users\xxxxx\Downloads\Mitigate-master\Utils.cs(299,29,299,33): error CS1031: Type expected
1>C:\Users\xxxxx\Downloads\Mitigate-master\Utils.cs(299,29,299,33): error CS1026: ) expected
1>C:\Users\xxxxx\Downloads\Mitigate-master\Utils.cs(299,33,299,34): error CS1002: ; expected
1>C:\Users\xxxxx\Downloads\Mitigate-master\Utils.cs(299,33,299,34): error CS1513: } expected
========== Rebuild All: 0 succeeded, 1 failed, 0 skipped ==========

P.S. Telegram is the worst way to contact anyone.

**Comment by moullos** [comment]
Hi Rich,

I am having trouble reproducing your issue and I have never really tested the project with VS 2015. Can you try VS 2019? I have made some changes that might help. Let me know how it goes. 

Finally, thank you for the submitting the first issue in the project. Hopefully, I will come up with a better way to contact me than Telegram.

**Comment by richrumble** [comment]
I was able to do it with the community/free 2019 version... I will try again in 2015 if you think the changes you made may make a difference. The ReadMe talked about pre-compiled binaries and I never could locate those so I tried to compile with what I already had installed. Compiled it just fine. Ran it with FULL and VERBOSE as local-admin, and seemed to work! As non-admin some registry reads failed and it barf'd. I think I see some results that I don't 100% agree with but I'm going to cross my I's and dot my T's first before I create any other tickets ;) Pretty cool tool so far though!
P.S. Win-7-64-bit works so far, going to test on other OS versions too.

**Comment by moullos** [comment]
Hi Rich,

You can access the pre-compiled binaries under releases [here](https://github.com/moullos/Mitigate/releases). Let me know for any specific findings that seem inaccurate. I will happily take a look and fix them. 

Happy to hear that it works on Win7. Never really tested it on that :)
