### ISSUE TITLE
 Unable to obtain latest Mitre Att&CK information. Please ensure that the device is connected to the internet.

### ISSUE THREAD

**Issue by VBoucher** [moullos/Mitigate#3]
When executing with the following command (with and without admin privileges):
`.\Mitigate.exe -OutFile=results.json`

The following error message appear : 

> -> Unable to obtain latest Mitre Att&CK information. Please ensure that the device is connected to the internet.

![image](https://user-images.githubusercontent.com/33044970/134277703-7a6cb9bb-5ad3-4094-9ad5-7ed4323bfc64.png)

Please take note that nothing on my device would indicate (at first sight) a network problem.

**Comment by moullos** [comment]
Thank you for letting me know @VBoucher.

I have just pushed a small update (334ddf09772c15a9fa0fe9391b2db44893c2355e)  that seems to resolve the issue ( The root cause had to do with an SSL issues). 

Can you kindly let me know whether this resolves the issue on your machine as well?

**Comment by VBoucher** [comment]
Hello,

Sorry for the huge delay. It worked. I no longer have the problem.
