### ISSUE TITLE
Output json to MITRE ATT&CK Navigator 3.0 doesn't parse correctly.

### ISSUE THREAD

**Issue by VBoucher** [moullos/Mitigate#4]
Hello,

Any json output json file doesn't parse correctly in the new version of Navigator :
![image](https://user-images.githubusercontent.com/33044970/142808614-8aa222ea-a367-4d4d-b6cc-964c46f6d39a.png)

If you click OK, it shows a tiny version without text :
![image](https://user-images.githubusercontent.com/33044970/142808649-c38cf89d-de19-473e-b68b-7e98ed314587.png)

Probably because the version 3.0 is not compatible with version 4.2

**Comment by moullos** [comment]
Hi @VBoucher. I am working on a newer version and a major overhaul of the project where this is resolved. It is still very much WIP, while I am going through bugs and preparing the documentation. I am planning on releasing it sometime next month; in the meantime feel free to test it out using the dev  branch.

**Comment by moullos** [comment]
Should be now resolved with the latest version
